// Custom Worker entry: wraps the OpenNext-generated handler so we can add a
// scheduled() handler for cron triggers (OpenNext v1 only exports fetch).
// wrangler bundles this file; `.open-next/worker.js` is generated by cf:build.

// @ts-ignore - generated at build time by opennextjs-cloudflare
import handler from "./.open-next/worker.js";

interface Env {
  CRON_SECRET: string;
  NEXT_PUBLIC_APP_URL?: string;
  [key: string]: unknown;
}

export default {
  fetch: handler.fetch,

  async scheduled(
    _controller: ScheduledController,
    env: Env,
    ctx: ExecutionContext
  ) {
    const baseUrl = env.NEXT_PUBLIC_APP_URL || "https://tasbihfy.com";
    // Loopback through the OpenNext handler — no external network hop
    ctx.waitUntil(
      handler.fetch(
        new Request(`${baseUrl}/api/cron/send-reminders`, {
          method: "POST",
          headers: { authorization: `Bearer ${env.CRON_SECRET}` },
        }),
        env,
        ctx
      )
    );
  },
} satisfies ExportedHandler<Env>;
