// Quran API constants and configurations

// Quran text scripts metadata
export const QURAN_SCRIPTS = {
  indopak: {
    id: "indopak",
    name: "Indopak",
    description: "Commonly used in South Asia",
    apiEndpoint: "indopak",
    fieldName: "text_indopak",
  },
  uthmani: {
    id: "uthmani",
    name: "Uthmani",
    description: "Traditional Uthmani script with full diacritical marks",
    apiEndpoint: "uthmani",
    fieldName: "text_uthmani",
  },
  uthmani_simple: {
    id: "uthmani_simple",
    name: "Uthmani Simple",
    description: "Simplified Uthmani script for easier reading",
    apiEndpoint: "uthmani_simple",
    fieldName: "text_uthmani_simple",
  },
  imlaei: {
    id: "imlaei",
    name: "Imlaei Simple",
    description: "Simple script without special characters",
    apiEndpoint: "imlaei",
    fieldName: "text_imlaei",
  },
} as const;

// Default translations to use when no user preference is set
export const DEFAULT_TRANSLATIONS = {
  english: {
    name: "Sahih International",
    author: "Sahih International",
    id: 0, // Will be resolved from API by name matching
    language: "english",
  },
  urdu: {
    name: "Bayan Ul Quran - Dr. Israr Ahmad",
    author: "Dr. Israr Ahmad",
    id: 0, // Will be resolved from API by name matching
    language: "urdu",
  },
} as const;

// Legacy constant for backward compatibility
export const TRANSLATION_RESOURCES = {
  english: DEFAULT_TRANSLATIONS.english,
  urdu: DEFAULT_TRANSLATIONS.urdu,
} as const;

// Default tafsir IDs (fallback values)
export const DEFAULT_TAFSIR_IDS = {
  english: 1, // Common English tafsir ID
  arabic: 2, // Common Arabic tafsir ID
  urdu: 3, // Common Urdu tafsir ID
} as const;

// Available tafsir resources (deprecated - kept for backward compatibility)
export const TAFSIR_RESOURCES = {
  "en-tafisr-ibn-kathir": {
    name: "Tafsir Ibn Kathir",
    language: "English",
    slug: "en-tafisr-ibn-kathir",
  },
  "en-tafsir-maarif-ul-quran": {
    name: "Maarif ul Quran",
    language: "English",
    slug: "en-tafsir-maarif-ul-quran",
  },
  "ur-tafseer-usmani": {
    name: "Tafseer-e-Usmani",
    language: "Urdu",
    slug: "ur-tafseer-usmani",
  },
} as const;

// Audio reciters
export const AUDIO_RECITERS = {
  "mishari-al-afasy": {
    id: 5,
    name: "Mishari Rashid al-Afasy",
    arabic_name: "مشاري بن راشد العفاسي",
    relative_path: "mishari_al_afasy",
  },
  "abdul-basit": {
    id: 1,
    name: "Abdul Basit Abdul Samad",
    arabic_name: "عبد الباسط عبد الصمد",
    relative_path: "abdul_basit_murattal",
  },
  "sa-ad-al-ghamdi": {
    id: 3,
    name: "Sa'ad Al-Ghamdi",
    arabic_name: "سعد الغامدي",
    relative_path: "sa_ad_al_ghamdi",
  },
} as const;

// Surah metadata (for quick reference without API calls)
export const SURAH_METADATA = [
  {
    id: 1,
    name: "Al-Fatihah",
    transliteration: "Al-Faatiha",
    translation: "The Opening",
    total_verses: 7,
    type: "meccan" as const,
  },
  {
    id: 2,
    name: "Al-Baqarah",
    transliteration: "Al-Baqara",
    translation: "The Cow",
    total_verses: 286,
    type: "medinan" as const,
  },
  {
    id: 3,
    name: "Ali 'Imran",
    transliteration: "Aal-i-Imraan",
    translation: "Family of Imran",
    total_verses: 200,
    type: "medinan" as const,
  },
  {
    id: 4,
    name: "An-Nisa",
    transliteration: "An-Nisaa",
    translation: "The Women",
    total_verses: 176,
    type: "medinan" as const,
  },
  {
    id: 5,
    name: "Al-Ma'idah",
    transliteration: "Al-Maaida",
    translation: "The Table Spread",
    total_verses: 120,
    type: "medinan" as const,
  },
  {
    id: 6,
    name: "Al-An'am",
    transliteration: "Al-An'aam",
    translation: "The Cattle",
    total_verses: 165,
    type: "meccan" as const,
  },
  {
    id: 7,
    name: "Al-A'raf",
    transliteration: "Al-A'raaf",
    translation: "The Heights",
    total_verses: 206,
    type: "meccan" as const,
  },
  {
    id: 8,
    name: "Al-Anfal",
    transliteration: "Al-Anfaal",
    translation: "The Spoils of War",
    total_verses: 75,
    type: "medinan" as const,
  },
  {
    id: 9,
    name: "At-Tawbah",
    transliteration: "At-Tawba",
    translation: "The Repentance",
    total_verses: 129,
    type: "medinan" as const,
  },
  {
    id: 10,
    name: "Yunus",
    transliteration: "Yunus",
    translation: "Jonah",
    total_verses: 109,
    type: "meccan" as const,
  },
  {
    id: 11,
    name: "Hud",
    transliteration: "Hud",
    translation: "Hud",
    total_verses: 123,
    type: "meccan" as const,
  },
  {
    id: 12,
    name: "Yusuf",
    transliteration: "Yusuf",
    translation: "Joseph",
    total_verses: 111,
    type: "meccan" as const,
  },
  {
    id: 13,
    name: "Ar-Ra'd",
    transliteration: "Ar-Ra'd",
    translation: "The Thunder",
    total_verses: 43,
    type: "medinan" as const,
  },
  {
    id: 14,
    name: "Ibrahim",
    transliteration: "Ibrahim",
    translation: "Abraham",
    total_verses: 52,
    type: "meccan" as const,
  },
  {
    id: 15,
    name: "Al-Hijr",
    transliteration: "Al-Hijr",
    translation: "The Rocky Tract",
    total_verses: 99,
    type: "meccan" as const,
  },
  {
    id: 16,
    name: "An-Nahl",
    transliteration: "An-Nahl",
    translation: "The Bee",
    total_verses: 128,
    type: "meccan" as const,
  },
  {
    id: 17,
    name: "Al-Isra",
    transliteration: "Al-Israa",
    translation: "The Night Journey",
    total_verses: 111,
    type: "meccan" as const,
  },
  {
    id: 18,
    name: "Al-Kahf",
    transliteration: "Al-Kahf",
    translation: "The Cave",
    total_verses: 110,
    type: "meccan" as const,
  },
  {
    id: 19,
    name: "Maryam",
    transliteration: "Maryam",
    translation: "Mary",
    total_verses: 98,
    type: "meccan" as const,
  },
  {
    id: 20,
    name: "Taha",
    transliteration: "Taa-Haa",
    translation: "Ta-Ha",
    total_verses: 135,
    type: "meccan" as const,
  },
  {
    id: 21,
    name: "Al-Anbya",
    transliteration: "Al-Anbiyaa",
    translation: "The Prophets",
    total_verses: 112,
    type: "meccan" as const,
  },
  {
    id: 22,
    name: "Al-Hajj",
    transliteration: "Al-Hajj",
    translation: "The Pilgrimage",
    total_verses: 78,
    type: "medinan" as const,
  },
  {
    id: 23,
    name: "Al-Mu'minun",
    transliteration: "Al-Muminoon",
    translation: "The Believers",
    total_verses: 118,
    type: "meccan" as const,
  },
  {
    id: 24,
    name: "An-Nur",
    transliteration: "An-Noor",
    translation: "The Light",
    total_verses: 64,
    type: "medinan" as const,
  },
  {
    id: 25,
    name: "Al-Furqan",
    transliteration: "Al-Furqaan",
    translation: "The Criterion",
    total_verses: 77,
    type: "meccan" as const,
  },
  {
    id: 26,
    name: "Ash-Shu'ara",
    transliteration: "Ash-Shu'araa",
    translation: "The Poets",
    total_verses: 227,
    type: "meccan" as const,
  },
  {
    id: 27,
    name: "An-Naml",
    transliteration: "An-Naml",
    translation: "The Ant",
    total_verses: 93,
    type: "meccan" as const,
  },
  {
    id: 28,
    name: "Al-Qasas",
    transliteration: "Al-Qasas",
    translation: "The Stories",
    total_verses: 88,
    type: "meccan" as const,
  },
  {
    id: 29,
    name: "Al-'Ankabut",
    transliteration: "Al-'Ankaboot",
    translation: "The Spider",
    total_verses: 69,
    type: "meccan" as const,
  },
  {
    id: 30,
    name: "Ar-Rum",
    transliteration: "Ar-Room",
    translation: "The Romans",
    total_verses: 60,
    type: "meccan" as const,
  },
  {
    id: 31,
    name: "Luqman",
    transliteration: "Luqman",
    translation: "Luqman",
    total_verses: 34,
    type: "meccan" as const,
  },
  {
    id: 32,
    name: "As-Sajdah",
    transliteration: "As-Sajda",
    translation: "The Prostration",
    total_verses: 30,
    type: "meccan" as const,
  },
  {
    id: 33,
    name: "Al-Ahzab",
    transliteration: "Al-Ahzaab",
    translation: "The Clans",
    total_verses: 73,
    type: "medinan" as const,
  },
  {
    id: 34,
    name: "Saba",
    transliteration: "Saba",
    translation: "Sheba",
    total_verses: 54,
    type: "meccan" as const,
  },
  {
    id: 35,
    name: "Fatir",
    transliteration: "Faatir",
    translation: "Originator",
    total_verses: 45,
    type: "meccan" as const,
  },
  {
    id: 36,
    name: "Ya-Sin",
    transliteration: "Yaseen",
    translation: "Ya Sin",
    total_verses: 83,
    type: "meccan" as const,
  },
  {
    id: 37,
    name: "As-Saffat",
    transliteration: "As-Saaffaat",
    translation: "Those who set the Ranks",
    total_verses: 182,
    type: "meccan" as const,
  },
  {
    id: 38,
    name: "Sad",
    transliteration: "Saad",
    translation: "The Letter Sad",
    total_verses: 88,
    type: "meccan" as const,
  },
  {
    id: 39,
    name: "Az-Zumar",
    transliteration: "Az-Zumar",
    translation: "The Troops",
    total_verses: 75,
    type: "meccan" as const,
  },
  {
    id: 40,
    name: "Ghafir",
    transliteration: "Ghaafir",
    translation: "The Forgiver",
    total_verses: 85,
    type: "meccan" as const,
  },
  {
    id: 41,
    name: "Fussilat",
    transliteration: "Fussilat",
    translation: "Explained in Detail",
    total_verses: 54,
    type: "meccan" as const,
  },
  {
    id: 42,
    name: "Ash-Shuraa",
    transliteration: "Ash-Shooraa",
    translation: "The Consultation",
    total_verses: 53,
    type: "meccan" as const,
  },
  {
    id: 43,
    name: "Az-Zukhruf",
    transliteration: "Az-Zukhruf",
    translation: "The Ornaments of Gold",
    total_verses: 89,
    type: "meccan" as const,
  },
  {
    id: 44,
    name: "Ad-Dukhan",
    transliteration: "Ad-Dukhaan",
    translation: "The Smoke",
    total_verses: 59,
    type: "meccan" as const,
  },
  {
    id: 45,
    name: "Al-Jathiyah",
    transliteration: "Al-Jaathiya",
    translation: "The Crouching",
    total_verses: 37,
    type: "meccan" as const,
  },
  {
    id: 46,
    name: "Al-Ahqaf",
    transliteration: "Al-Ahqaaf",
    translation: "The Wind-Curved Sandhills",
    total_verses: 35,
    type: "meccan" as const,
  },
  {
    id: 47,
    name: "Muhammad",
    transliteration: "Muhammad",
    translation: "Muhammad",
    total_verses: 38,
    type: "medinan" as const,
  },
  {
    id: 48,
    name: "Al-Fath",
    transliteration: "Al-Fath",
    translation: "The Victory",
    total_verses: 29,
    type: "medinan" as const,
  },
  {
    id: 49,
    name: "Al-Hujurat",
    transliteration: "Al-Hujuraat",
    translation: "The Rooms",
    total_verses: 18,
    type: "medinan" as const,
  },
  {
    id: 50,
    name: "Qaf",
    transliteration: "Qaaf",
    translation: "The Letter Qaf",
    total_verses: 45,
    type: "meccan" as const,
  },
  {
    id: 51,
    name: "Adh-Dhariyat",
    transliteration: "Adh-Dhaariyaat",
    translation: "The Winnowing Winds",
    total_verses: 60,
    type: "meccan" as const,
  },
  {
    id: 52,
    name: "At-Tur",
    transliteration: "At-Toor",
    translation: "The Mount",
    total_verses: 49,
    type: "meccan" as const,
  },
  {
    id: 53,
    name: "An-Najm",
    transliteration: "An-Najm",
    translation: "The Star",
    total_verses: 62,
    type: "meccan" as const,
  },
  {
    id: 54,
    name: "Al-Qamar",
    transliteration: "Al-Qamar",
    translation: "The Moon",
    total_verses: 55,
    type: "meccan" as const,
  },
  {
    id: 55,
    name: "Ar-Rahman",
    transliteration: "Ar-Rahmaan",
    translation: "The Beneficent",
    total_verses: 78,
    type: "meccan" as const,
  },
  {
    id: 56,
    name: "Al-Waqi'ah",
    transliteration: "Al-Waaqia",
    translation: "The Inevitable",
    total_verses: 96,
    type: "meccan" as const,
  },
  {
    id: 57,
    name: "Al-Hadid",
    transliteration: "Al-Hadeed",
    translation: "The Iron",
    total_verses: 29,
    type: "medinan" as const,
  },
  {
    id: 58,
    name: "Al-Mujadila",
    transliteration: "Al-Mujaadila",
    translation: "The Pleading Woman",
    total_verses: 22,
    type: "medinan" as const,
  },
  {
    id: 59,
    name: "Al-Hashr",
    transliteration: "Al-Hashr",
    translation: "The Exile",
    total_verses: 24,
    type: "medinan" as const,
  },
  {
    id: 60,
    name: "Al-Mumtahanah",
    transliteration: "Al-Mumtahana",
    translation: "She that is to be examined",
    total_verses: 13,
    type: "medinan" as const,
  },
  {
    id: 61,
    name: "As-Saff",
    transliteration: "As-Saff",
    translation: "The Ranks",
    total_verses: 14,
    type: "medinan" as const,
  },
  {
    id: 62,
    name: "Al-Jumu'ah",
    transliteration: "Al-Jumu'a",
    translation: "The Congregation",
    total_verses: 11,
    type: "medinan" as const,
  },
  {
    id: 63,
    name: "Al-Munafiqun",
    transliteration: "Al-Munaafiqoon",
    translation: "The Hypocrites",
    total_verses: 11,
    type: "medinan" as const,
  },
  {
    id: 64,
    name: "At-Taghabun",
    transliteration: "At-Taghaabun",
    translation: "The Mutual Disillusion",
    total_verses: 18,
    type: "medinan" as const,
  },
  {
    id: 65,
    name: "At-Talaq",
    transliteration: "At-Talaaq",
    translation: "The Divorce",
    total_verses: 12,
    type: "medinan" as const,
  },
  {
    id: 66,
    name: "At-Tahrim",
    transliteration: "At-Tahreem",
    translation: "The Prohibition",
    total_verses: 12,
    type: "medinan" as const,
  },
  {
    id: 67,
    name: "Al-Mulk",
    transliteration: "Al-Mulk",
    translation: "The Sovereignty",
    total_verses: 30,
    type: "meccan" as const,
  },
  {
    id: 68,
    name: "Al-Qalam",
    transliteration: "Al-Qalam",
    translation: "The Pen",
    total_verses: 52,
    type: "meccan" as const,
  },
  {
    id: 69,
    name: "Al-Haqqah",
    transliteration: "Al-Haaqqah",
    translation: "The Reality",
    total_verses: 52,
    type: "meccan" as const,
  },
  {
    id: 70,
    name: "Al-Ma'arij",
    transliteration: "Al-Ma'aarij",
    translation: "The Ascending Stairways",
    total_verses: 44,
    type: "meccan" as const,
  },
  {
    id: 71,
    name: "Nuh",
    transliteration: "Nooh",
    translation: "Noah",
    total_verses: 28,
    type: "meccan" as const,
  },
  {
    id: 72,
    name: "Al-Jinn",
    transliteration: "Al-Jinn",
    translation: "The Jinn",
    total_verses: 28,
    type: "meccan" as const,
  },
  {
    id: 73,
    name: "Al-Muzzammil",
    transliteration: "Al-Muzzammil",
    translation: "The Enshrouded One",
    total_verses: 20,
    type: "meccan" as const,
  },
  {
    id: 74,
    name: "Al-Muddaththir",
    transliteration: "Al-Muddaththir",
    translation: "The Cloaked One",
    total_verses: 56,
    type: "meccan" as const,
  },
  {
    id: 75,
    name: "Al-Qiyamah",
    transliteration: "Al-Qiyaamah",
    translation: "The Resurrection",
    total_verses: 40,
    type: "meccan" as const,
  },
  {
    id: 76,
    name: "Al-Insan",
    transliteration: "Al-Insaan",
    translation: "The Man",
    total_verses: 31,
    type: "medinan" as const,
  },
  {
    id: 77,
    name: "Al-Mursalat",
    transliteration: "Al-Mursalaat",
    translation: "The Emissaries",
    total_verses: 50,
    type: "meccan" as const,
  },
  {
    id: 78,
    name: "An-Naba",
    transliteration: "An-Naba",
    translation: "The Tidings",
    total_verses: 40,
    type: "meccan" as const,
  },
  {
    id: 79,
    name: "An-Nazi'at",
    transliteration: "An-Naazi'aat",
    translation: "Those who drag forth",
    total_verses: 46,
    type: "meccan" as const,
  },
  {
    id: 80,
    name: "Abasa",
    transliteration: "'Abasa",
    translation: "He Frowned",
    total_verses: 42,
    type: "meccan" as const,
  },
  {
    id: 81,
    name: "At-Takwir",
    transliteration: "At-Takweer",
    translation: "The Overthrowing",
    total_verses: 29,
    type: "meccan" as const,
  },
  {
    id: 82,
    name: "Al-Infitar",
    transliteration: "Al-Infitaar",
    translation: "The Cleaving",
    total_verses: 19,
    type: "meccan" as const,
  },
  {
    id: 83,
    name: "Al-Mutaffifin",
    transliteration: "Al-Mutaffifeen",
    translation: "The Defrauding",
    total_verses: 36,
    type: "meccan" as const,
  },
  {
    id: 84,
    name: "Al-Inshiqaq",
    transliteration: "Al-Inshiqaaq",
    translation: "The Splitting Open",
    total_verses: 25,
    type: "meccan" as const,
  },
  {
    id: 85,
    name: "Al-Buruj",
    transliteration: "Al-Burooj",
    translation: "The Mansions of the Stars",
    total_verses: 22,
    type: "meccan" as const,
  },
  {
    id: 86,
    name: "At-Tariq",
    transliteration: "At-Taariq",
    translation: "The Morning Star",
    total_verses: 17,
    type: "meccan" as const,
  },
  {
    id: 87,
    name: "Al-A'la",
    transliteration: "Al-A'laa",
    translation: "The Most High",
    total_verses: 19,
    type: "meccan" as const,
  },
  {
    id: 88,
    name: "Al-Ghashiyah",
    transliteration: "Al-Ghaashiya",
    translation: "The Overwhelming",
    total_verses: 26,
    type: "meccan" as const,
  },
  {
    id: 89,
    name: "Al-Fajr",
    transliteration: "Al-Fajr",
    translation: "The Dawn",
    total_verses: 30,
    type: "meccan" as const,
  },
  {
    id: 90,
    name: "Al-Balad",
    transliteration: "Al-Balad",
    translation: "The City",
    total_verses: 20,
    type: "meccan" as const,
  },
  {
    id: 91,
    name: "Ash-Shams",
    transliteration: "Ash-Shams",
    translation: "The Sun",
    total_verses: 15,
    type: "meccan" as const,
  },
  {
    id: 92,
    name: "Al-Layl",
    transliteration: "Al-Layl",
    translation: "The Night",
    total_verses: 21,
    type: "meccan" as const,
  },
  {
    id: 93,
    name: "Ad-Duhaa",
    transliteration: "Ad-Duhaa",
    translation: "The Morning Hours",
    total_verses: 11,
    type: "meccan" as const,
  },
  {
    id: 94,
    name: "Ash-Sharh",
    transliteration: "Ash-Sharh",
    translation: "The Relief",
    total_verses: 8,
    type: "meccan" as const,
  },
  {
    id: 95,
    name: "At-Tin",
    transliteration: "At-Teen",
    translation: "The Fig",
    total_verses: 8,
    type: "meccan" as const,
  },
  {
    id: 96,
    name: "Al-'Alaq",
    transliteration: "Al-'Alaq",
    translation: "The Clot",
    total_verses: 19,
    type: "meccan" as const,
  },
  {
    id: 97,
    name: "Al-Qadr",
    transliteration: "Al-Qadr",
    translation: "The Power",
    total_verses: 5,
    type: "meccan" as const,
  },
  {
    id: 98,
    name: "Al-Bayyinah",
    transliteration: "Al-Bayyina",
    translation: "The Clear Proof",
    total_verses: 8,
    type: "medinan" as const,
  },
  {
    id: 99,
    name: "Az-Zalzalah",
    transliteration: "Az-Zalzala",
    translation: "The Earthquake",
    total_verses: 8,
    type: "medinan" as const,
  },
  {
    id: 100,
    name: "Al-'Adiyat",
    transliteration: "Al-'Aadiyaat",
    translation: "The Courser",
    total_verses: 11,
    type: "meccan" as const,
  },
  {
    id: 101,
    name: "Al-Qari'ah",
    transliteration: "Al-Qaari'a",
    translation: "The Calamity",
    total_verses: 11,
    type: "meccan" as const,
  },
  {
    id: 102,
    name: "At-Takathur",
    transliteration: "At-Takaathur",
    translation: "The Rivalry in world increase",
    total_verses: 8,
    type: "meccan" as const,
  },
  {
    id: 103,
    name: "Al-'Asr",
    transliteration: "Al-'Asr",
    translation: "The Declining Day",
    total_verses: 3,
    type: "meccan" as const,
  },
  {
    id: 104,
    name: "Al-Humazah",
    transliteration: "Al-Humaza",
    translation: "The Traducer",
    total_verses: 9,
    type: "meccan" as const,
  },
  {
    id: 105,
    name: "Al-Fil",
    transliteration: "Al-Feel",
    translation: "The Elephant",
    total_verses: 5,
    type: "meccan" as const,
  },
  {
    id: 106,
    name: "Quraysh",
    transliteration: "Quraysh",
    translation: "Quraysh",
    total_verses: 4,
    type: "meccan" as const,
  },
  {
    id: 107,
    name: "Al-Ma'un",
    transliteration: "Al-Maa'oon",
    translation: "The Small kindnesses",
    total_verses: 7,
    type: "meccan" as const,
  },
  {
    id: 108,
    name: "Al-Kawthar",
    transliteration: "Al-Kawthar",
    translation: "The Abundance",
    total_verses: 3,
    type: "meccan" as const,
  },
  {
    id: 109,
    name: "Al-Kafirun",
    transliteration: "Al-Kaafiroon",
    translation: "The Disbelievers",
    total_verses: 6,
    type: "meccan" as const,
  },
  {
    id: 110,
    name: "An-Nasr",
    transliteration: "An-Nasr",
    translation: "The Divine Support",
    total_verses: 3,
    type: "medinan" as const,
  },
  {
    id: 111,
    name: "Al-Masad",
    transliteration: "Al-Masad",
    translation: "The Palm Fiber",
    total_verses: 5,
    type: "meccan" as const,
  },
  {
    id: 112,
    name: "Al-Ikhlas",
    transliteration: "Al-Ikhlaas",
    translation: "The Sincerity",
    total_verses: 4,
    type: "meccan" as const,
  },
  {
    id: 113,
    name: "Al-Falaq",
    transliteration: "Al-Falaq",
    translation: "The Daybreak",
    total_verses: 5,
    type: "meccan" as const,
  },
  {
    id: 114,
    name: "An-Nas",
    transliteration: "An-Naas",
    translation: "Mankind",
    total_verses: 6,
    type: "meccan" as const,
  },
] as const;

// Default settings
export const DEFAULT_QURAN_SETTINGS = {
  translationLanguages: ["english"],
  selectedTranslations: process.env.NODE_ENV === "production" ? [20] : [85], // Production: Saheeh International, Test: Haleem
  selectedScript: "uthmani" as const, // Default to Uthmani script
  arabicFontSize: 18,
  translationFontSize: 16,
  showTransliteration: true,
  showWordByWord: false,
  showVerseNumbers: true,
  selectedReciter: "mishari-al-afasy", // Legacy field for backward compatibility
  selectedRecitationId: 7, // Default to Mishari Rashid al-`Afasy (ID: 7)
  autoScroll: true,
  repeatVerse: false,
  autoPlayNext: true,
} as const;

// Cache durations (in milliseconds)
export const CACHE_DURATION = {
  SURAH_LIST: 24 * 60 * 60 * 1000, // 24 hours
  SURAH_DATA: 7 * 24 * 60 * 60 * 1000, // 7 days
  TRANSLATIONS: 7 * 24 * 60 * 60 * 1000, // 7 days
  TAFSIR: 7 * 24 * 60 * 60 * 1000, // 7 days
} as const;
